### ISSUE TITLE
how to use basic tensorflow code 

### ISSUE THREAD

**Issue by koliaok** [taki0112/AdamP-Tensorflow#1]
basic tensorflow code:
`learning_loss = .....
train_op = tf.compat.v1.train.AdamOptimizer(learning_rate=0.001).minimize(learning_loss)`

I think your AdamP only keras complie code and another tensorflow basic code use "tf.AdamP(learning_rate=0.001, betas=(0.9, 0.999), weight_decay=1e-2).minimize(learning_loss, var_list=variable_var_list)", so I need code "variable_var_list" list variable.
but basic tensorflow code not need var_list

How to use AdamP in basic tensorflow code ?

Thank you

**Comment by taki0112** [comment]
For example
here is my test code
```python
@tf.function
def train_step(image, labels, network, optimizer, training=True):
    with tf.GradientTape() as tape:
        logits = network(image, training=training)
        loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=labels))

    train_variable = network.trainable_variables
    gradient = tape.gradient(loss, train_variable)

    optimizer.apply_gradients(zip(gradient, train_variable))

    return loss
```

**Comment by koliaok** [comment]
> For example
> here is my test code
> 
> ```python
> @tf.function
> def train_step(image, labels, network, optimizer, training=True):
>     with tf.GradientTape() as tape:
>         logits = network(image, training=training)
>         loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=labels))
> 
>     train_variable = network.trainable_variables
>     gradient = tape.gradient(loss, train_variable)
> 
>     optimizer.apply_gradients(zip(gradient, train_variable))
> 
>     return loss
> ```

Thank you ~
but need make save the trainable_variables to list if I make NN network
