### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'assign_sub'

### ISSUE THREAD

**Issue by templeblock** [taki0112/AdamP-Tensorflow#2]
hi @taki0112  in tensorflow 2.2.0, i got the error.

adamp_tf.py:123 _resource_apply_dense
        var_update = var.assign_sub(step_size * perturb, use_locking=self._use_locking)

    AttributeError: 'Tensor' object has no attribute 'assign_sub'

how to fix it?

**Comment by taki0112** [comment]
my code is 
`var_update = state_ops.assign_sub(var, step_size * perturb, use_locking=self._use_locking)`

where is `var.assign_sub` ?

**Comment by templeblock** [comment]
@taki0112 var_update = state_ops.assign_sub(var, step_size * perturb, use_locking=self._use_locking) got the same error.

**Comment by templeblock** [comment]
when set the argument "weight_decay" to 0.0 ,it passed.

**Comment by taki0112** [comment]
can you try this ?
`var = state_ops.assign(var, var - step_size * perturb, use_locking=self._use_locking)`

**Comment by cpuimage** [comment]
@taki0112     

var_update = state_ops.assign(var, var - step_size * perturb, use_locking=self._use_locking)
   /.local/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py:228 assign
        return ref.assign(value, name=name)

    AttributeError: 'Tensor' object has no attribute 'assign'

**Comment by templeblock** [comment]
@taki0112   var_update = state_ops.assign(var, var - step_size * perturb, use_locking=self._use_locking)
/.local/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py:228 assign
        return ref.assign(value, name=name)

    AttributeError: 'Tensor' object has no attribute 'assign'

it look like this code,change the "var" type  :
 ```python
# Weight decay
        if self.weight_decay > 0:
            var = var * (1 - coefficients['lr'] * coefficients['weight_decay'] * wd_ratio)```

**Comment by taki0112** [comment]
could you try this ? 

`var = var * (1 - coefficients['lr'] * coefficients['weight_decay'] * wd_ratio)`
->
`var = state_ops.assign(var, var * (1 - coefficients['lr'] * coefficients['weight_decay'] * wd_ratio), use_locking=self._use_locking)`

**Comment by templeblock** [comment]
it passed!!!

> could you try this ?
> 
> `var = var * (1 - coefficients['lr'] * coefficients['weight_decay'] * wd_ratio)`
> ->
> `var = state_ops.assign(var, var * (1 - coefficients['lr'] * coefficients['weight_decay'] * wd_ratio), use_locking=self._use_locking)`
