### ISSUE TITLE
betas error

### ISSUE THREAD

**Issue by 1920039** [taki0112/AdamP-Tensorflow#5]
Hello.

I was executing mnist with CNN on Colab and encountered an error on betas.
When I remove the betas arg, my codes executes fine.
I attach a screenshot and also a Colab address of my codes.

https://colab.research.google.com/drive/18hCSxHkEvSQNllCjXXpYov3Q2R60FAyU?usp=sharing

![AdamP error](https://user-images.githubusercontent.com/65439606/116417450-3a245900-a876-11eb-822a-15ec54ace799.png)

**Comment by taki0112** [comment]
sorry for my mistake.
try this.
`AdamP(learning_rate=0.001, beta_1=0.9, beta_2=0.999, weight_decay=1e-2)`
not `betas`, do `beta_1, beta2`

**Comment by 1920039** [comment]
It's working now.
Thank you!
